<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmallGreen.Common\SmallGreen.Common.csproj" />
    <ProjectReference Include="..\SmallGreen.Entity\SmallGreen.Entity.csproj" />
  </ItemGroup>

</Project>